# Site settings
title: Bacsstories
email: 
author: Vivien Chen and Emily Zou
description: 
url:

# Build settings
sass:
  sass_dir: sass

# Paginate
paginate: 3
paginate_path: "/posts/page:num/"

# Plugins
plugins:
  - jekyll-paginate
